### ISSUE TITLE
Real-Time Data Collection and Prediction Update

### ISSUE THREAD

**Issue by LakshmanKishore** [LakshmanKishore/fullBatteryPrediction#1]
## Description
The current implementation of the battery prediction app collects data over a fixed duration of 2 minutes with a 5-second interval, and the prediction graph is generated at the end of this period.

The goal of this issue is to enhance the app to collect and display data in real-time, updating the prediction graph dynamically as new data points are collected. 

### Tasks
- [ ] Refactor data collection mechanism to capture data every 5 seconds.
- [ ] Implement real-time updates for the prediction graph.
- [ ] Integrate the linear regression (OLS) technique for dynamic prediction.
- [ ] Update user interface to reflect real-time data points and predictions.
- [ ] Update documentation to reflect changes made.

**Comment by hengj10** [comment]
Is this task to dynamically predict using real-time updates of the measured actual values even for the period before the actual values are updated? Should the prediction also be updated every time the actual values are updated?

**Comment by hengj10** [comment]
Hello, I'd like to ask if this task involves continuously dynamically predicting the subsequent curve based on real-time updates of the measured curve (the part before the measured values are updated)?

**Comment by LakshmanKishore** [comment]
Thank you for showing your interest!!
This was a simple project that I had build during my college days to learn about linear regression and about web development, and to learn about integrating ML in web.

In the current state of the application, the data is collected first and then the prediction happens.
This could be enhanced with collecting the data and for every five seconds or after some duration the graph should update and the prediction should happen.

You can check the current project live [here](https://lakshmankishore.github.io/fullBatteryPrediction/)

Instead of predictions happening after 2 minutes, it would be good to update the graph:
* every few seconds.
* whenever there is an increment in charging.
This was my goal.
